'use client';
import type { Metadata } from "next";
import { AppShell, Burger, MantineProvider } from '@mantine/core';
import { useDisclosure } from "@mantine/hooks";
import { Inter } from "next/font/google";
import '@mantine/core/styles.css';
import { SessionProvider } from 'next-auth/react';
import Header from "./ui/header";
import Sidebar from "./ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [opened, { toggle }] = useDisclosure();

  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <MantineProvider>
          <SessionProvider> 
            <AppShell
              header={{ height: 60 }}
              navbar={{
                width: 300,
                breakpoint: 'sm',
                collapsed: { mobile: !opened },
              }}
              padding="md"
            >
              <AppShell.Header>
                <Burger
                  opened={opened}
                  onClick={toggle}
                  hiddenFrom="sm"
                  size="sm"
                />

                <Header />
              </AppShell.Header>

              <AppShell.Navbar p="md">
                <Sidebar />
              </AppShell.Navbar>

              <AppShell.Main>
                {children}
              </AppShell.Main>
            </AppShell>
          </SessionProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
